[supervisord]
nodaemon=true

[program:update_credentials]
command=/bin/bash -c "/etc/credentials.sh"

[program:apache2]
command=service apache2 start
autostart = true
autorestart = false
stopasgroup=true

[program:module_installer]
command=/bin/bash /etc/module_installer.sh
autostart = true
autorestart = false
user = qloapps
environment = user="qloapps"

[program:ssh]
command=service ssh start
autostart = true
autorestart = false
stopasgroup=true
